### PR TITLE
Set up GitHub Actions CI, and add some very basic tests

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Note: the tests will fail until https://github.com/GunnarFarneback/RegistryInstances.jl/pull/3 is merged.

**Comment by GunnarFarneback** [comment]
Thanks. Shouldn't this PR be trying to run CI?

**Comment by GunnarFarneback** [comment]
Thanks. Shouldn't this PR be trying to run CI?

**Comment by DilumAluthge** [comment]
Try closing and reopening it? Maybe it'll trigger if you do it.

**Comment by DilumAluthge** [comment]
Looks green on master.

**Pull request merged**
